# Generated by Django 4.2.30 on 2026-05-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Export'), ('UTILITY', 'Utility Feed'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('ingestion_mode', models.CharField(choices=[('FILE_UPLOAD', 'File Upload'), ('API_PULL', 'API Pull')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('document', models.FileField(blank=True, upload_to='source_documents/%Y/%m/%d/')),
                ('payload_preview', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='core.datasourceprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Export'), ('UTILITY', 'Utility Feed'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('ingestion_mode', models.CharField(choices=[('FILE_UPLOAD', 'File Upload'), ('API_PULL', 'API Pull')], max_length=20)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ISSUES', 'Completed With Issues'), ('FAILED', 'Failed')], max_length=32)),
                ('requested_by', models.CharField(default='System Seed', max_length=120)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('flagged_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to='core.datasourceprofile')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to='ingestion.sourcedocument')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning')], max_length=16)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ingestion.importrun')),
            ],
            options={
                'ordering': ['import_run_id', 'severity', 'line_number', 'id'],
            },
        ),
    ]
