# Generated by Django 4.2.30 on 2026-05-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Export'), ('UTILITY', 'Utility Feed'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('category', models.CharField(choices=[('FUEL', 'Fuel Combustion'), ('PROCUREMENT', 'Purchased Goods'), ('ELECTRICITY', 'Purchased Electricity'), ('AIR_TRAVEL', 'Air Travel'), ('HOTEL', 'Hotel Stay'), ('GROUND', 'Ground Transport')], max_length=24)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=16)),
                ('base_unit', models.CharField(max_length=32)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=14)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['source_type', 'category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=80)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
            ],
            options={
                'ordering': ['tenant__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('sector', models.CharField(max_length=80)),
                ('reporting_currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Export'), ('UTILITY', 'Utility Feed'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('alias', models.CharField(max_length=120)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.facility')),
            ],
            options={
                'ordering': ['facility__tenant__name', 'alias'],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='DataSourceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Export'), ('UTILITY', 'Utility Feed'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('ingestion_mode', models.CharField(choices=[('FILE_UPLOAD', 'File Upload'), ('API_PULL', 'API Pull')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'source_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Export'), ('UTILITY', 'Utility Feed'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('category', models.CharField(choices=[('FUEL', 'Fuel Combustion'), ('PROCUREMENT', 'Purchased Goods'), ('ELECTRICITY', 'Purchased Electricity'), ('AIR_TRAVEL', 'Air Travel'), ('HOTEL', 'Hotel Stay'), ('GROUND', 'Ground Transport')], max_length=24)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=16)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('external_id', models.CharField(max_length=120)),
                ('source_line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source_document_identifier', models.CharField(max_length=120)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=240)),
                ('quantity_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=32)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=32)),
                ('currency_code', models.CharField(blank=True, max_length=3)),
                ('spend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estimated_kg_co2e', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('suspicion_score', models.PositiveSmallIntegerField(default=0)),
                ('suspicion_reasons', models.JSONField(blank=True, default=list)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=120)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('edited_fields', models.JSONField(blank=True, default=list)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='core.datasourceprofile')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='core.facility')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
