# Generated by Django 4.2.30 on 2026-05-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='import_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='ingestion.importrun'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='ingestion.sourcedocument'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='facilityalias',
            unique_together={('source_type', 'alias')},
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='datasourceprofile',
            unique_together={('tenant', 'source_type', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='activityrecord',
            unique_together={('tenant', 'source_type', 'external_id')},
        ),
    ]
